#!/bin/bash
echo What is the IP address on the PC?
read pc_ip
export ROS_MASTER_URI=http://$pc_ip:11311
export ROS_IP=$(hostname -I)
export ROS_HOSTNAME=$(hostname).mshome.net
env | grep ROS_MASTER_URI
env | grep ROS_IP

echo Done.
