#!/usr/bin/env python
import rospy, sys
from romi_soccer.cloud_maker import cloud_maker
sys.path.append('../src/romi_soccer/src/romi_soccer')
from romi_soccer.romi_finder_simple import RomiFinderSimple
if __name__ == '__main__':
    rospy.init_node('romi_finder_simple')
    cloud = cloud_maker()
    try:
        rospy.loginfo('Initializing node...')
        romi_finder = RomiFinderSimple(cloud)
    except rospy.ROSInterruptException:
            pass