#!/usr/bin/env python
import rospy, sys
sys.path.append('../src/romi_soccer/src/romi_soccer')
from romi_soccer.json_grabber import JSONGrabber
if __name__=='__main__':
    rospy.init_node('json_grabber')
    try:
        rospy.loginfo('Initializing node...')
        jason = JSONGrabber()
    except rospy.ROSInterruptException:
            pass
