#!/usr/bin/env python
import rospy,sys
sys.path.append('../src/romi_soccer/src/romi_soccer')
from romi_soccer.image_mapper import ImageMapper
if __name__=='__main__':
    rospy.init_node('image_mapper')
    try:
        rospy.loginfo('Initializing node...')
        map = ImageMapper()
    except rospy.ROSInterruptException:
            pass
