#!/usr/bin/env python
import rospy, sys
sys.path.append('../src/romi_soccer/src/romi_soccer')
from romi_soccer.odom_calculator import OdomCalc
if __name__ == '__main__':
    rospy.init_node('odom_calculator')
    try:
        rospy.loginfo('Initializing node...')
        odom_calculator = OdomCalc()
    except rospy.ROSInterruptException:
            pass
