#!/usr/bin/env python
import rospy, sys
sys.path.append('../src/romi_soccer/src/romi_soccer')
from romi_soccer.romi_poser import RomiPoser
if __name__ == '__main__':
    rospy.init_node('romi_poser')
    try:
        rospy.loginfo('Initializing node...')
        romi_poser = RomiPoser()
    except rospy.ROSInterruptException:
            pass
